name: 'Publish to CPAN'
description: 'Publish a CPAN module'
inputs:
  cpan-user: 
    description: "Username for authenticating with PAUSE/CPAN"
    required: true
  cpan-password: 
    description: "Password for authenticating with PAUSE/CPAN"
    required: true
  working-directory:
    description: "Path within the repo to the folder where the mix.exs file lives"
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - run: sudo apt-get --assume-yes update 
      shell: bash
    - run: sudo apt-get --assume-yes install perl cpanminus
      shell: bash
    - run: perl -v
      shell: bash
    - run: cpanm --notest --sudo Dist::Zilla
      shell: bash
    - run: dzil --version
      shell: bash
    - name: install dependencies required for building
      run: dzil authordeps --missing | cpanm
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: build package
      run: dzil build
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: upload to cpan
      run: |
        cpan-upload --user $CPAN_USER --password $CPAN_PASSWORD *.tar.gz
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        CPAN_USER: ${{ inputs.cpan-user }}
        CPAN_PASSWORD: ${{ inputs.cpan-password }}
