name: Test

on:
  push:

jobs:
  test-publish-cpan:
    name: Publishes a perl module to CPAN from a dist.ini
    runs-on: ubuntu-latest
    environment: Publish to CPAN
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - name: Set unique package version
        id: set-version
        run: |
          version=0.0.$GITHUB_RUN_NUMBER
          sed -i "s/0.0.0/$version/g" dist.ini
          echo "version=$version" >> $GITHUB_OUTPUT
        working-directory: "test"
      - name: Test the action
        uses: ./
        with:
          cpan-user: ${{ secrets.CPAN_USER }}
          cpan-password: ${{ secrets.CPAN_PASSWORD }}
          working-directory: "test"
      - name: Assert that latest published package version is available on CPAN
        timeout-minutes: 60
        run: |
          version=v${{ steps.set-version.outputs.version }}
          url=https://metacpan.org/release/CUKEBOT/Cucumber-Test-Release-Automation-$version
          echo "Checking for $version on CPAN servers at $url"
          while ! curl --silent --fail $url > /dev/null
          do
            echo -n "."
            sleep 5
          done
