name: Test

on:
  push:
    branches:
      - main

jobs:
  test-publish-cpan:
    name: Publishes a perl module to CPAN from a dist.ini
    runs-on: ubuntu-latest
    environment: Publish to CPAN
    steps:
      - uses: actions/checkout@v2
      - name: Set unique package version
        id: set-version
        run: |
          version=0.0.$GITHUB_RUN_NUMBER
          sed -i "s/0.0.0/$version/g" VERSION
          echo "::set-output name=version::$version"
        working-directory: "perl"
      - name: Test the action
        uses: ./
        with:
          cpan-user: ${{ secrets.CPAN_USER }}
          cpan-password: ${{ secrets.CPAN_PASSWORD }}
          working-directory: "perl"
      - name: Assert that latest published package version is available on CPAN
        timeout-minutes: 1
        run: |
          version=0.0.$GITHUB_RUN_NUMBER
          curl --silent --fail https://metacpan.org/release/CUKEBOT/Cucumber-Test-Release-Automation-v$version > /dev/null
